### PR TITLE
Adding websocket source and showing scalability.

### PR DESCRIPTION
**Pull request by markusthoemmes**
As per title.

TODOs:
- Proper image name in the YAML

### CODE REVIEW

**Comment by matzew** [comment]
:eyes:

**Comment by matzew** [comment]
```
2018/11/29 06:42:25 Openshift Http Request Dumper received a message: POST / HTTP/1.1
Host: helloworld-openshift.myproject.svc.cluster.local
Accept-Encoding: gzip
Ce-Cloudeventsversion: 0.1
Ce-Eventid: 9d5e7a1b-695f-4786-b0e5-7d477f664511
Ce-Eventtime: 2018-11-29T06:41:15.056598031Z
Ce-Eventtype: websocket-event
Ce-Source: wss://api.usb.urbanobservatory.ac.uk/stream
Content-Length: 738
Content-Type: application/json
User-Agent: Go-http-client/1.1
X-B3-Parentspanid: fa1c3d384549e3b6
X-B3-Sampled: 1
X-B3-Spanid: 19cef1860cdd8a93
X-B3-Traceid: fa1c3d384549e3b6
X-Forwarded-For: 127.0.0.1
X-Forwarded-Proto: http
X-Request-Id: 62538a68-4f45-9130-9aab-e8f72d9c8afb

"eyJzaWduYWwiOjIsImRhdGEiOnsiYnJva2VyYWdlIjp7ImJyb2tlciI6eyJpZCI6IkJNUy1VU0ItRy1QWEM1MCIsIm1ldGEiOnsicHJvdG9jb2wiOiJCQUNORVQiLCJidWlsZGluZyI6IlVyYmFuIFNjaWVuY2VzIEJ1aWxkaW5nIiwiYnVpbGRpbmdGbG9vciI6IkcifX0sImlkIjoiUGx0MDInTWV0ZXJzJ1N3SW5jb21lJ1Bvd2VyIiwibWV0YSI6eyJidWlsZGluZ1BsYW50Um9vbSI6IjIifX0sImVudGl0eSI6eyJuYW1lIjoiVXJiYW4gU2NpZW5jZXMgQnVpbGRpbmc6IEZsb29yIEc6IFBsYW50IFJvb20gMiIsIm1ldGEiOnsiYnVpbGRpbmciOiJVcmJhbiBTY2llbmNlcyBCdWlsZGluZyIsImJ1aWxkaW5nRmxvb3IiOiJHIn19LCJmZWVkIjp7Im1ldHJpYyI6IlBvd2VyIChLdykiLCJtZXRhIjp7fX0sInRpbWVzZXJpZXMiOnsidW5pdCI6ImtpbG93YXR0cyIsInZhbHVlIjp7InRpbWUiOiIyMDE4LTExLTI5VDA2OjQxOjE1LjYwNVoiLCJ0aW1lQWNjdXJhY3kiOjQuNTU2LCJkYXRhIjoyNy41

```

**Review by matzew — APPROVED** [review]
did receive messages, over the (locally) setup `kafka` channel

**Comment by matzew** [comment]
Also, with the `in-memory-channel`, I do see _scaling_:

```
helloworld-openshift-00001-deployment-6f9b48896b-44glh   3/3       Running     0          16m
helloworld-openshift-00001-deployment-6f9b48896b-shx68   3/3       Running     0          27s
helloworld-openshift-00001-deployment-6f9b48896b-wgglz   3/3       Running     0          27s
```

Will check w/ the kafka channel...

**Comment by matzew** [comment]
I see traffic in all three nodes, wondering, what's the reason that _active_ pods sometimes die?

```
helloworld-openshift-00001-deployment-6f9b48896b-44glh   3/3       Running     0          20m
helloworld-openshift-00001-deployment-6f9b48896b-tqcvq   3/3       Running     0          21s
helloworld-openshift-00001-deployment-6f9b48896b-wgglz   3/3       Running     0          4m
```

not sure why the second died, while under load, and than is running as a new one

**Comment by markusthoemmes** [comment]
@matzew The autoscaler is not perfect, it sometimes overshoots a bit, then throws the pod away, overshoots again. It might flicker a bit if the load "on the edge".

**Comment by matzew** [comment]
I am also getting some errors on the dispatcher of the `in-memory-channel`:

```
{"level":"error","ts":1543474763.8430464,"caller":"fanout/fanout_handler.go:108","msg":"Fanout had an error","error":"Unable to complete request unexpected HTTP response, expected 2xx, got 503","stacktrace":"github.com/knative/eventing/pkg/sidecar/fanout.(*Handler).dispatch\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:108\ngithub.com/knative/eventing/pkg/sidecar/fanout.createReceiverFunction.func1\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:86\ngithub.com/knative/eventing/pkg/buses.(*MessageReceiver).HandleRequest\n\t/go/src/github.com/knative/eventing/pkg/buses/message_receiver.go:119\ngithub.com/knative/eventing/pkg/sidecar/fanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:91\ngithub.com/knative/eventing/pkg/sidecar/multichannelfanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go:119\ngithub.com/knative/eventing/pkg/sidecar/swappable.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/swappable/swappable.go:104\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/google-golang/src/net/http/server.go:2740\nnet/http.(*conn).serve\n\t/usr/lib/google-golang/src/net/http/server.go:1846"}
{"level":"error","ts":1543474763.8547335,"caller":"fanout/fanout_handler.go:108","msg":"Fanout had an error","error":"Unable to complete request unexpected HTTP response, expected 2xx, got 503","stacktrace":"github.com/knative/eventing/pkg/sidecar/fanout.(*Handler).dispatch\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:108\ngithub.com/knative/eventing/pkg/sidecar/fanout.createReceiverFunction.func1\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:86\ngithub.com/knative/eventing/pkg/buses.(*MessageReceiver).HandleRequest\n\t/go/src/github.com/knative/eventing/pkg/buses/message_receiver.go:119\ngithub.com/knative/eventing/pkg/sidecar/fanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:91\ngithub.com/knative/eventing/pkg/sidecar/multichannelfanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go:119\ngithub.com/knative/eventing/pkg/sidecar/swappable.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/swappable/swappable.go:104\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/google-golang/src/net/http/server.go:2740\nnet/http.(*conn).serve\n\t/usr/lib/google-golang/src/net/http/server.go:1846"}
{"level":"error","ts":1543474763.854715,"caller":"fanout/fanout_handler.go:108","msg":"Fanout had an error","error":"Unable to complete request unexpected HTTP response, expected 2xx, got 503","stacktrace":"github.com/knative/eventing/pkg/sidecar/fanout.(*Handler).dispatch\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:108\ngithub.com/knative/eventing/pkg/sidecar/fanout.createReceiverFunction.func1\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:86\ngithub.com/knative/eventing/pkg/buses.(*MessageReceiver).HandleRequest\n\t/go/src/github.com/knative/eventing/pkg/buses/message_receiver.go:119\ngithub.com/knative/eventing/pkg/sidecar/fanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:91\ngithub.com/knative/eventing/pkg/sidecar/multichannelfanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go:119\ngithub.com/knative/eventing/pkg/sidecar/swappable.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/swappable/swappable.go:104\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/google-golang/src/net/http/server.go:2740\nnet/http.(*conn).serve\n\t/usr/lib/google-golang/src/net/http/server.go:1846"}
{"level":"error","ts":1543474763.8580158,"caller":"fanout/fanout_handler.go:108","msg":"Fanout had an error","error":"Unable to complete request unexpected HTTP response, expected 2xx, got 503","stacktrace":"github.com/knative/eventing/pkg/sidecar/fanout.(*Handler).dispatch\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:108\ngithub.com/knative/eventing/pkg/sidecar/fanout.createReceiverFunction.func1\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:86\ngithub.com/knative/eventing/pkg/buses.(*MessageReceiver).HandleRequest\n\t/go/src/github.com/knative/eventing/pkg/buses/message_receiver.go:119\ngithub.com/knative/eventing/pkg/sidecar/fanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:91\ngithub.com/knative/eventing/pkg/sidecar/multichannelfanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go:119\ngithub.com/knative/eventing/pkg/sidecar/swappable.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/swappable/swappable.go:104\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/google-golang/src/net/http/server.go:2740\nnet/http.(*conn).serve\n\t/usr/lib/google-golang/src/net/http/server.go:1846"}
{"level":"error","ts":1543474763.8613796,"caller":"fanout/fanout_handler.go:108","msg":"Fanout had an error","error":"Unable to complete request unexpected HTTP response, expected 2xx, got 503","stacktrace":"github.com/knative/eventing/pkg/sidecar/fanout.(*Handler).dispatch\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:108\ngithub.com/knative/eventing/pkg/sidecar/fanout.createReceiverFunction.func1\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:86\ngithub.com/knative/eventing/pkg/buses.(*MessageReceiver).HandleRequest\n\t/go/src/github.com/knative/eventing/pkg/buses/message_receiver.go:119\ngithub.com/knative/eventing/pkg/sidecar/fanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:91\ngithub.com/knative/eventing/pkg/sidecar/multichannelfanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go:119\ngithub.com/knative/eventing/pkg/sidecar/swappable.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/swappable/swappable.go:104\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/google-golang/src/net/http/server.go:2740\nnet/http.(*conn).serve\n\t/usr/lib/google-golang/src/net/http/server.go:1846"}
{"level":"error","ts":1543474763.861592,"caller":"fanout/fanout_handler.go:108","msg":"Fanout had an error","error":"Unable to complete request unexpected HTTP response, expected 2xx, got 503","stacktrace":"github.com/knative/eventing/pkg/sidecar/fanout.(*Handler).dispatch\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:108\ngithub.com/knative/eventing/pkg/sidecar/fanout.createReceiverFunction.func1\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:86\ngithub.com/knative/eventing/pkg/buses.(*MessageReceiver).HandleRequest\n\t/go/src/github.com/knative/eventing/pkg/buses/message_receiver.go:119\ngithub.com/knative/eventing/pkg/sidecar/fanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:91\ngithub.com/knative/eventing/pkg/sidecar/multichannelfanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go:119\ngithub.com/knative/eventing/pkg/sidecar/swappable.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/swappable/swappable.go:104\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/google-golang/src/net/http/server.go:2740\nnet/http.(*conn).serve\n\t/usr/lib/google-golang/src/net/http/server.go:1846"}
{"level":"error","ts":1543474763.8613887,"caller":"fanout/fanout_handler.go:108","msg":"Fanout had an error","error":"Unable to complete request unexpected HTTP response, expected 2xx, got 503","stacktrace":"github.com/knative/eventing/pkg/sidecar/fanout.(*Handler).dispatch\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:108\ngithub.com/knative/eventing/pkg/sidecar/fanout.createReceiverFunction.func1\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:86\ngithub.com/knative/eventing/pkg/buses.(*MessageReceiver).HandleRequest\n\t/go/src/github.com/knative/eventing/pkg/buses/message_receiver.go:119\ngithub.com/knative/eventing/pkg/sidecar/fanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:91\ngithub.com/knative/eventing/pkg/sidecar/multichannelfanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go:119\ngithub.com/knative/eventing/pkg/sidecar/swappable.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/swappable/swappable.go:104\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/google-golang/src/net/http/server.go:2740\nnet/http.(*conn).serve\n\t/usr/lib/google-golang/src/net/http/server.go:1846"}
{"level":"error","ts":1543474763.8659909,"caller":"fanout/fanout_handler.go:108","msg":"Fanout had an error","error":"Unable to complete request unexpected HTTP response, expected 2xx, got 503","stacktrace":"github.com/knative/eventing/pkg/sidecar/fanout.(*Handler).dispatch\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:108\ngithub.com/knative/eventing/pkg/sidecar/fanout.createReceiverFunction.func1\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:86\ngithub.com/knative/eventing/pkg/buses.(*MessageReceiver).HandleRequest\n\t/go/src/github.com/knative/eventing/pkg/buses/message_receiver.go:119\ngithub.com/knative/eventing/pkg/sidecar/fanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/fanout/fanout_handler.go:91\ngithub.com/knative/eventing/pkg/sidecar/multichannelfanout.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/multichannelfanout/multi_channel_fanout_handler.go:119\ngithub.com/knative/eventing/pkg/sidecar/swappable.(*Handler).ServeHTTP\n\t/go/src/github.com/knative/eventing/pkg/sidecar/swappable/swappable.go:104\nnet/http.serverHandler.ServeHTTP\n\t/usr/lib/google-golang/src/net/http/server.go:2740\nnet/http.(*conn).serve\n\t/usr/lib/google-golang/src/net/http/server.go:1846"}
{"level":"info","ts":1543474764.0917065,"caller":"buses/message_receiver.go:110","msg":"Received request for testchannel.myproject.channels.cluster.local"}
{"level":"info","ts":1543474764.091934,"caller":"buses/message_dispatcher.go:93","msg":"Dispatching message to http://helloworld-openshift.myproject.svc.cluster.local/"}
{"level":"info","ts":1543474764.092372,"caller":"buses/message_receiver.go:110","msg":"Received request for testchannel.myproject.channels.cluster.local"}
{"level":"info","ts":1543474764.0925546,"caller":"buses/message_dispatcher.go:93","msg":"Dispatching message to http://helloworld-openshift.myproject.svc.cluster.local/"}
{"level":"info","ts":1543474764.1342053,"caller":"buses/message_receiver.go:110","msg":"Received request for testchannel.myproject.channels.cluster.local"}
{"level":"info","ts":1543474764.1343806,"caller":"buses/message_dispatcher.go:93","msg":"Dispatching message to http://helloworld-openshift.myproject.svc.cluster.local/"}

```

I came back after some time, and all "helloworld" pods were gone

**Review by vdemeester — APPROVED** [review]
LGTM :wink: 
Let's refine in follow-up PRs :wink:

**Pull request merged**
