### PR TITLE
app rename

### PR DESCRIPTION
**Pull request by matzew**
We have the dumpy app !

### CODE REVIEW

**Comment by matzew** [comment]
I guess the actual repo does need to be renamed ... @markusthoemmes @vdemeester, right ?

**Comment by matzew** [comment]
one more fix; did rebase !

**Comment by vdemeester** [comment]
> I guess the actual repo does need to be renamed ... @markusthoemmes @vdemeester, right ?

I would think so indeed :angel:

**Comment by jcrossley3** [comment]
I approve this PR with all my heart /lgtm

**Review by vdemeester — APPROVED** [review]
LGTM :tiger:

**Review by markusthoemmes — COMMENTED** [review]
To get it out of my pending reviews list.

**Comment by matzew** [comment]
:joy_cat:

**Pull request merged**
